### ISSUE TITLE
Default to HTTPS

### ISSUE THREAD

**Issue by asymmetric** [chubin/rate.sx#13]
It would be cool if the rate.sx defaulted to HTTPS. AFAIK two ways of doing this would be 301 redirects or HSTS.

**Comment by chubin** [comment]
Yes, you are right. The only problem here is that if you use curl, you have to add `-L` explicitly for the redirects to be processed. Otherwise you will see an ugly message in HTML format.
It is being handled automatically in browser, but not in curl.

**Comment by asymmetric** [comment]
You're right, it's already happening in the browser. I checked on [ssllabs](https://www.ssllabs.com/ssltest/analyze.html?d=rate.sx) and HSTS also seems to be on, good job! :)

I guess this can be closed then.
