### ISSUE TITLE
Bug: doesn't seem to handle arguments

### ISSUE THREAD

**Issue by C0DK** [chubin/rate.sx#24]
I really love your different APIs and tools. They are really reat.

I am trying to use it on my ncurses status window, but can't get output without ANSI colors:
`http://rate.sx/?T`
giving me this output:
![image](https://user-images.githubusercontent.com/9048078/56467151-7ae17000-641b-11e9-8ac4-d326847a67b2.png)

same with: `curl 'rate.sx/?qT&n=20'` which displays both footer and header, which seems to  be  a bug. the `n` argument, however, works. It just seems to be "T" and "q". also would it be possible to add the "f" argument to rate.sx, much like on wttr.in, not that i don't want to subscribe to your twitter, but i don't need to be reminded when ever i am checking the weather.

Hope you have a possibility to fix it,

**Comment by chubin** [comment]
@C0DK Casper, please test.
It should work now

**Comment by C0DK** [comment]
sorry i never answered. works now. awesome work :) Thanks. Now i can add it to my status box
