### ISSUE TITLE
Dependency missing prevents building from source

### ISSUE THREAD

**Issue by Salastil** [chubin/rate.sx#26]
Currently termdata is missing from Pypi so its not possible to source from requirements.txt. Has this dependency changed names? Punching it into search engines has turned up nothing, I can't seem to find an archive of it, or a description of what it did.

**Comment by chubin** [comment]
@Salastil I fixed the name of the dependency, please try again.
Please also keep in mind, that the repository does not contain historical data,
that means if you install it it will provide historical data only from the time, when it was installed
