### ISSUE TITLE
use unicode instaed of codepage 0 switching

### ISSUE THREAD

**Issue by yne** [chubin/rate.sx#3]
As described here https://github.com/chubin/wttr.in/issues/151#issuecomment-350023601 the `rate.sx` use codepage switching escape command to draw it boxes instead of simply using the unicode equivalent.

Could you draw the rate.sx table layout using unicode in both application ?

**Comment by chubin** [comment]
I have that after the issue is fixed, the problem reported by @davep in twitter will disappear also 
https://twitter.com/davepdotorg/status/939085767070113792

**Comment by davep** [comment]
Excellent. I'll remove `rate-sx-unboxify` once that's done.

**Comment by yne** [comment]
Can't wait to look at my eth/btc from my vita :D

**Comment by chubin** [comment]
@yne Hope you will see it soon :) (do you want to see etc/btc pair? because crypto pairs are not yet supported, only crypto/non-crypto at the moment). Do you have something like a status line in your terminal on Vita by the way? Do you use there tmux or something like that?

**Comment by chubin** [comment]
Please test, it should work now

**Comment by davep** [comment]
I appear to still be seeing the codepage switching approach.

**Comment by chubin** [comment]
Could you please try gbp.rate.sx?

**Comment by davep** [comment]
Okay, yeah, that looks good with gbp.sate.sx; showing just great inside GNU Emacs.

![screen shot 2017-12-08 at 19 36 04](https://user-images.githubusercontent.com/28237/33782065-1569d88e-dc4f-11e7-9547-c9e14dcfd470.png)

When this is the default I'll tweak the code.

**Comment by chubin** [comment]
Perfect! Now it should work for rate.sx also (it was a caching issue). Now the cache on the endpoint was updated, so it should work for all queries.

What seems a little bit strange to me that the timestamp and the frame are of different colours. They should be the same actually. Interesting.

@yne Now it will work on Vita also (I hope)

**Comment by yne** [comment]
It's working, I had to add support for the SGR "2" (used to darken the box) and it look fine now, thanks for the fix.
![out](https://user-images.githubusercontent.com/5113053/33800686-71545aa6-dd45-11e7-8492-8c678d326e21.png)

I don't need crypto/crypto pairing charts. Thanks ;)
