### ISSUE TITLE
SSL certificate has expired - https

### ISSUE THREAD

**Issue by WANDEX** [chubin/rate.sx#32]
Is it on my end, or is this the result for everyone?
Output of:
```sh
$ curl https://rate.sx

curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by chubin** [comment]
Sorry, it was my fault; should be fixed now; please test and thank you for reporting

**Comment by WANDEX** [comment]
SSL certificate has expired again, thank you in advance for fixing. :rocket:

**Comment by chubin** [comment]
I think at the time of writing (10 min ago), was it already updated. Anyway. please check

**Comment by WANDEX** [comment]
Yes, probably i typed text for too long :) rate.sx works now, thx.

wttr.in also need the same fix, i am sure you already know that. :1st_place_medal:

**Comment by chubin** [comment]
Should be now working too :+1:

**Comment by WANDEX** [comment]
Yes, it's fixed :tada: thx. :partying_face:
