### ISSUE TITLE
Malformed request kills server

### ISSUE THREAD

**Issue by min0ru** [chubin/rate.sx#33]
I was accidently found out that malformed request kills server with 504 Gateway Time-out error.
Request example ("h" char in place of number parameter):
    curl rate.sx/btc@hh

**Comment by chubin** [comment]
I am not sure, but I suppose that it was just a temporary high load issue. At least I can't reproduce the problem anymore

**Comment by min0ru** [comment]
Same here. Now i'am getting error "ERROR: Invalid time interval specification: hh". So it looks like no issue anymore. Thank you!
Maybe it is worth to scale service a bit with more processes (by using uwsgi / gunicorn) in case of any overload issues.
