### ISSUE TITLE
curl rate.sx/avax not working

### ISSUE THREAD

**Issue by jaderebrasil** [chubin/rate.sx#38]
Hello, I can't curl for avax coin 
I mean, when I run
$ curl 'rate.sx?n=30'

The result shows Avax
![image](https://user-images.githubusercontent.com/5043579/111076488-36f22b00-84cb-11eb-85aa-e5a812bb5440.png)

But 
$ curl 'rate.sx/avax' 
not works as expected
![image](https://user-images.githubusercontent.com/5043579/111076514-5426f980-84cb-11eb-9b9d-b6b8958f5ebf.png)

**Comment by jaderebrasil** [comment]
Oh, I just realized that avax is not in 
$ curl 'rate.sx/:coins'

I think this is not an issue only avax is not supported. But still, avax appears on the list given by
$ curl 'rate.sx?n=30'

**Comment by chubin** [comment]
@jaderebrasil Jader. thank you for reporting it. AVAX is fully supported now

![Selection_147](https://user-images.githubusercontent.com/3875145/115716429-77ba4b00-a379-11eb-9749-f9faca96f089.png)

Please test

**Comment by jaderebrasil** [comment]
Working perfectly. Thank you very much!
