### ISSUE TITLE
No Ravencoin?

### ISSUE THREAD

**Issue by PastLife** [chubin/rate.sx#40]
Ravencoin is in top 100 
Can I get a graph for RVN? 
`curl rate.sx/rvn` 
prints out `ERROR: Invalid coin/currency name: RVN`

**Comment by chubin** [comment]
@PastLife Ravencoin is supported now. Please test, and thank you for reporting

![Selection_148](https://user-images.githubusercontent.com/3875145/115716840-e7303a80-a379-11eb-8295-0b93b37569bc.png)

**Comment by PastLife** [comment]
You are amazing!! Thank you so much for this wizardry.

**Comment by chubin** [comment]
Ravencoin to the Moon!
