### ISSUE TITLE
Uniswap (UNI) and Filecoin (FIL) support?

### ISSUE THREAD

**Issue by JayBrown** [chubin/rate.sx#46]
Does rate.sx support UNI and FIL?

I tried `curl rate.sx/fil` and `curl rate.sx/uni`, and I'm getting `ERROR: Invalid coin/currency name`.

If there's no support, will it be possible to add it?

**Comment by chubin** [comment]
Please test; now it should work

**Comment by JayBrown** [comment]
Works! Thank you.
