### ISSUE TITLE
Prints Dollar Sign for any currency

### ISSUE THREAD

**Issue by specs32** [chubin/rate.sx#47]
Hi,
since .. like 2 hours ago I get a $  sign instead of € sign when I query like this: 
`curl eur.rate.sx/xmr`
... `begin: $219.01 (Thu 27 00:10) // end: $205.60 (Fri 28 00:00)~` ...

**Comment by specs32** [comment]
To elaborate ...
I use following query : `curl eur.rate.sx/xmr |grep end |awk '{print ($8)}'`
That (now newly) spits out `$205.20` not `€205.20`
It would be nice if there were a single space between the currency and the value, so that I can filter that easier 🙈
I use this in my conky config and the dollar sign kind of messed it up ^^

**Comment by specs32** [comment]
Ok, I finally got annoyed enough by conkys error log ...
This works too, in case anyone is interested...
`curl eur.rate.sx/xmr | grep end | awk '{print $8}' | cut -d "\$" -f2`

**Comment by chubin** [comment]
This issue was fixed some time ago; please test if it works for you,
and thank you very much for reporting it.

**Comment by specs32** [comment]
It is fixed, thank you !!
