### ISSUE TITLE
Some tickers URLs not working

### ISSUE THREAD

**Issue by yerofey** [chubin/rate.sx#49]
Short URL for SOL & NEAR not working:
<img width="307" alt="Снимок экрана 2021-09-10 в 02 05 21" src="https://user-images.githubusercontent.com/1276038/132773913-15a9e429-ba73-43e5-93a5-00e6ac56ae1d.png">

**Comment by chubin** [comment]
Please check it again. They should work now

**Comment by yerofey** [comment]
Yep, now it's good. Thanks!
