### ISSUE TITLE
Call to get list of supported currencies

### ISSUE THREAD

**Issue by davep** [chubin/rate.sx#5]
From the [help page](http://rate.sx/:help):

```
Supported currencies:

    USD, AUD, CAD, CHF, CNY, EUR, GBP, IDR, JPY, KRW, RUB
```

It could be useful for other code that uses rate.sx if this list could be pulled from a URL, perhaps ideally with descriptions of currencies. If that were available then [code like this wouldn't be necessary](https://github.com/davep/rate-sx.el/blob/0bb108f73d83f0dafa34510accabb0c875128fa6/rate-sx.el#L39-L53) and third party code won't need to be updated any time you add another currency.

**Comment by chubin** [comment]
It is done now! There are two urls (/:coins and /:currencies) to get the list of the cryptocurrencies and list of the currencies with their names. The first column (in both cases is the (crypto)currency code and the rest is description). So you cal always split the line by the first space.
