### ISSUE TITLE
Add The Utility Bixos Token (UBXS)

### ISSUE THREAD

**Issue by emretepedev** [chubin/rate.sx#58]
We often use rate.sx in the office and we got pretty used to the ease and smart design it provides. Now we need rate.sx services for the calculations, tracking and daily use for our own token that we released to the market which has a great project behind it. Can you please include UBXS in rate.sx?

**Comment by chubin** [comment]
Unfortunately we have no data for it, because it is not in top 600 coins (by market cap).
We have information only about the top 600 coins in our database for the moment.
It will be automatically available at rate.sx as soon as it market cap will reach top600
