### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by joaofnds** [chubin/rate.sx#67]
any updates?

![image](https://user-images.githubusercontent.com/9938253/196007170-f6aacad2-2fea-49a2-8fc6-01c3f45cbd88.png)

**Comment by SilverScalp** [comment]
![Screenshot_20221016_110209](https://user-images.githubusercontent.com/93727591/196039648-9c5959c3-8208-4289-9f69-b2a49abeae02.png)
Lol, my status bar crashed haha

**Comment by joaofnds** [comment]
Looks like it is back up :tada:

**Comment by AlSchlo** [comment]
Down again :(
