### ISSUE TITLE
Add More Currencies

### ISSUE THREAD

**Issue by yne** [chubin/rate.sx#7]
The TOP10 cryptocurrency has changed, so supported list should be updated:
https://github.com/chubin/rate.sx/blob/master/lib/currencies.py#L56
to support request like: `/1ETH+1XRP+1ADA+1TRON`

**Comment by chubin** [comment]
Accepted. Several new currencies will be added soon.

**Comment by yne** [comment]
I tried to deploy the code on my local machine, but it seems that lots of instructions are bound to your personal environnement (uncommitted `calculator` module, some popen() with hardcoded path to your /home/).

**Comment by chubin** [comment]
@yne Yes, Rémy, you are right, there are currently some uncommitted changes indeed. I\m working on a major code update at the moment (this issue will be also fixed with this update), and in that update I will remove all local dependencies, or for the dependencies that can't be removed I'll provide API + description, how you can get all needed data

**Comment by yne** [comment]
I wanted to download+test the code so I can help you with this "More currencies" feature.

I'll wait for you then.

If you need any help, you can ask me :-)

**Comment by chubin** [comment]
I've the planned update and committed it on github. The code in the repository is completely identical to the code running on rate.sx now. It has no parts bound to my local environment now (if I didn't miss something, but I hope I didn't).

If you want to play with the code, you can just pull it and run locally. Keep in mind that it uses mongodb (that by default should run locally). You can install mongodb and start filling it with data using the collect script (it is in bin/). You have to run this script using cron every 5 minutes (I will add this information in the README file later). Or I can give you access to the rate.sx database.

Regarding currencies and cryptocurrencies support: now we support 31 currency and the top 500 cryptocurrencies. If some coin goes out of this top 500 list its rate becomes wrong: rate.sx shows the last seen rate. 

Now you can use cryptocurrencies not only for the calculator, but also as output units (you could use only normal currencies for that):

```
curl btc.rate.sx
curl btc.rate.sx/10000USD
```
In this case everything (including marketcap, sparks, changes etc.) 
are displayed in this cryptocurrency (not using its current rate but using its correct historical rate;
that means that for example spark for the current is a constant line consisting of zeros). 

This feature is not yet officially released (and not yet documented), but you can already use it :)
