### ISSUE TITLE
rate.sx is not responding

### ISSUE THREAD

**Issue by Wondertan** [chubin/rate.sx#71]

**Comment by ZeBadger** [comment]
Maybe there's some rate limiting?

matt@vps-09d2a406:~$ time curl usd.rate.sx/1GBP
1.20930079597

real    0m0.070s
user    0m0.006s
sys     0m0.006s
matt@vps-09d2a406:~$ time curl usd.rate.sx/10GBP
12.0930079597

real    0m59.926s
user    0m0.010s
sys     0m0.005s

**Comment by Wondertan** [comment]
I have no idea what happened but it started to work
